# Generated by Django 5.1.3 on 2024-11-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_years_event_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_desc',
            field=models.TextField(default='New event in history', max_length=300),
        ),
        migrations.AddField(
            model_name='events',
            name='event_title',
            field=models.TextField(default='New Historical Event', max_length=20),
        ),
    ]
