# Generated by Django 5.1.3 on 2024-11-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyFacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='years',
            name='event_year',
            field=models.IntegerField(default=2024),
        ),
    ]
